%%{init: {'theme':'dark'}}%%
graph TB
    node_1[New Node]
    node_2[New Node]
    node_3[New Node]
    node_4[New Node]
    node_5[New Node]
    node_6[New Node]
    node_7[New Node]
    node_2--> node_6
    node_6--> node_1