graph TB
    node_1[C]
    node_2[A]
    node_3[D]
    node_4[E]
    node_6[B]
    node_7[F]
    node_1778319364182[G]
    node_1778319442618[R]
    node_2--> node_6
    node_6--> node_1
    node_3--> node_4
    node_4--> node_1
    node_4--> node_7
    node_1778319364182--> node_1778319442618