flowchart TB
    frontend(logos:react前端层)
    backend(logos:nodejs后端层)
    database(logos:database数据层)
    web(serverWeb应用)
    api(gatewayAPI网关)
    auth(service认证服务)
    user(service用户服务)
    order(service订单服务)
    db(database主数据库)
    cache(cache缓存)
    L[L]
    T[T]
    B[B]
    web--> L
    api--> L
    api--> L
    api--> L
    auth--> T
    user--> T
    order--> T
    auth--> B
    user--> B